"""Clementi-Raimondi size-calibration factors for the atom cloud (hydrogenic model),
indexed by Z-1 (Z=1..92, the display range cap -- slater.MAX_DISPLAY_Z).
Scaling the cloud coordinates by FACTOR[z-1] makes the valence subshell mode
radius land on the Clementi-Raimondi literature value, keeping the model's own
internal shell structure. Elements without a CR value (Fr, Ra) are 1.0.

Consumers that render the hydrogenic model and so need HYDROGENIC factors:
pc/atom_view_pc.py's default (`--model hydrogenic`) path,
pc/atom_dissection_common.py's default_size_factor() fallback (shared with the
web viewer), and the web viewer itself. NOT micropython/atom_view.py, which
renders through the HFS tables now -- see hfs_atom_size_calib.py.

GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
"""

FACTOR = (
    1.0016, 0.9889, 0.7709, 0.7729, 0.9951, 0.9926, 1.0143, 1.0098,
    1.0120, 1.0337, 0.6885, 0.6933, 0.7556, 0.7490, 0.7540, 0.7597,
    0.7609, 0.7563, 0.6519, 0.6549, 0.6542, 0.6508, 0.6538, 0.6541,
    0.6529, 0.6507, 0.6506, 0.6532, 0.6502, 0.6502, 0.6781, 0.6792,
    0.6805, 0.6840, 0.6801, 0.6585, 0.6253, 0.6293, 0.6278, 0.6285,
    0.5549, 0.5491, 0.6260, 0.5464, 0.5437, 2.0504, 0.5276, 0.6243,
    0.6419, 0.6411, 0.6458, 0.6459, 0.6487, 0.6519, 0.2999, 0.3298,
    0.2676, 0.2538, 0.3220, 0.2685, 0.2672, 0.3102, 0.3011, 0.3197,
    0.2933, 0.2972, 0.2946, 0.2946, 0.2894, 0.2894, 0.2977, 0.2997,
    0.3019, 0.3045, 0.3095, 0.3173, 0.3211, 0.2874, 0.2945, 0.3402,
    0.3630, 0.4049, 0.4193, 0.4366, 0.4492, 0.4607, 1.0000, 1.0000,
    0.2248, 0.2179, 0.2075, 0.2018,
)
