"""Clementi-Raimondi size-calibration factors for the atom cloud (HFS-table model),
indexed by Z-1 (Z=1..92, the display range cap -- slater.MAX_DISPLAY_Z).
Scaling the cloud coordinates by FACTOR[z-1] makes the valence subshell mode
radius land on the Clementi-Raimondi literature value, keeping the model's own
internal shell structure. Elements without a CR value (Fr, Ra) are 1.0.

Same factors as src/physics/atom_size_calib.h (device C++). Consumed ONLY by
micropython/atom_view.py, which renders through hfs_radial_tables.py's tables
the same way the device does -- see pc/RUN_HFS.md's device note.

GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
"""

FACTOR = (
    0.9436, 1.0240, 1.0026, 1.0281, 1.0482, 1.0600, 1.0862, 1.1056,
    1.1190, 1.1484, 1.1012, 1.0805, 0.8374, 0.9743, 1.0086, 1.0368,
    1.0369, 1.0285, 1.1230, 1.0912, 1.1133, 1.1375, 1.1631, 1.1260,
    1.1986, 1.2096, 1.2170, 1.2335, 1.1759, 1.2618, 1.0082, 1.0600,
    1.0747, 1.0694, 1.0514, 1.0612, 1.1527, 1.1149, 1.1698, 1.2087,
    1.1751, 1.1715, 1.2250, 1.1838, 1.1788, 2.8822, 1.1796, 1.2450,
    1.0276, 1.0555, 1.0572, 1.0558, 1.0521, 1.0456, 1.1486, 1.1232,
    0.9276, 0.8976, 1.1546, 0.9781, 0.9888, 1.1668, 1.1460, 1.2169,
    1.1376, 1.1636, 1.1641, 1.1749, 1.1650, 1.1761, 1.2344, 1.2321,
    1.2292, 1.2319, 1.2452, 1.2539, 1.2476, 1.2117, 1.2137, 1.2716,
    0.9738, 1.0572, 1.0612, 1.0670, 1.0595, 1.0632, 1.0000, 1.0000,
    0.8691, 0.8438, 0.8270, 0.8152,
)
