"""Device-side (MicroPython) loader and radial source for the screened-
potential (HFS/atomSFE) atom model -- MicroPython counterpart of
src/physics/hfs_radial.h and pc/hfs_tables.py's RadialSource/HfsTables.

Reads hfs_tables.bin (generated by tools/hfs_table_gen.py from
pc/hfs_tables_reduced.npz) instead of a giant Python-literal module: a
~470KB source file of float literals would cost MicroPython a slow, RAM-
heavy compile just to import it, for no benefit over reading the identical
bytes off the filesystem the interpreter already runs from. The .bin file
deploys to the device root the same way every other file here does (see
main.py's docstring for the `mpremote ... fs cp -r micropython/. :`
incantation), so no separate deploy step is needed. Embedding the data
straight into flash instead of the filesystem (for MicroPython boards
without a usable one) is future work -- see
pc/screened_potential_model.md section 7.

Binary format (little-endian, packed with `struct` -- see
tools/hfs_table_gen.py's HEADER_FMT/ELEMENT_FMT/SUBSHELL_FMT, the single
source of truth this module's format strings below must keep matching):
    <HHH                gridSize, elementCount, subshellCount
    <f * gridSize        R -- shared log-uniform Bohr grid
    (<HB) * elementCount  ELEMENT[z-1] = (offset, count) into SUBSHELL/U
    (<BB) * subshellCount SUBSHELL[i] = (n, ell), i in [offset, offset+count)
    (<f * gridSize) * subshellCount   U[i], same index i, back to back

Only the header + R + ELEMENT + SUBSHELL (a few KB total) are read into RAM
by HfsTables(); each subshell's own u(r) row (gridSize * 4 bytes) is read
from the file ON DEMAND by source(), when that (Z, n, ell) is actually
selected -- the whole ~470KB table is never resident in RAM at once. This
matches how the table is actually used: atom_cloud.build_atom_point_cloud()
looks up each occupied subshell once per element switch (not once per frame
or per sampled point).

HfsTables keeps ONE file handle open for its own lifetime (opened in
__init__(), never closed) instead of a fresh open()/close() per source()
call -- measured on the C++ port's real hardware (src/physics/hfs_radial.cpp, same
read strategy against the same file format on SPIFFS): re-opening the file
once per subshell (7 opens for iron) inflated point-cloud build time from
~30-60ms to ~800-980ms, because filesystem open/close (an object-index
lookup) is the expensive part, not the seek/read that follows it. A held-
open file only needs seek()+read() per call.
"""

import array
import struct

import pointcloud

DEFAULT_PATH = 'hfs_tables.bin'

_HEADER_FMT = '<HHH'
_HEADER_SIZE = 6
_ELEMENT_FMT = '<HB'
_ELEMENT_SIZE = 3
_SUBSHELL_FMT = '<BB'
_SUBSHELL_SIZE = 2


class RadialSource:
    """One subshell's solved radial function -- same duck-typed interface as
    pc/hfs_tables.py's RadialSource, consumed by atom_cloud.py's
    radial_tables branch: `.r`, `.u`, `.max_r()`, `.R_lookup(r)`.
    """

    def __init__(self, r, u):
        self.r = r  # array.array('f', ...), the table's shared grid (not copied)
        self.u = u  # array.array('f', ...), this subshell's own u(r)

    def R_lookup(self, r):
        """R(r) = u(r)/r -- callable for init_orbital_sampler(radial_fn=...)."""
        if r <= 1e-9:
            return 0.0
        return pointcloud.interp_u(r, self.r, self.u) / r

    def max_r(self):
        return self.r[len(self.r) - 1]


class HfsTables:
    """Header/index resident in RAM; each subshell's u(r) read from `path`
    on demand by source() -- see module docstring."""

    def __init__(self, path=DEFAULT_PATH):
        self._path = path
        f = open(path, 'rb')
        grid_size, element_count, subshell_count = struct.unpack(_HEADER_FMT, f.read(_HEADER_SIZE))
        self.grid_size = grid_size
        self.element_count = element_count
        self.subshell_count = subshell_count

        self.r = array.array('f', f.read(4 * grid_size))

        element = []
        for _ in range(element_count):
            element.append(struct.unpack(_ELEMENT_FMT, f.read(_ELEMENT_SIZE)))
        self._element = element

        subshell = []
        for _ in range(subshell_count):
            subshell.append(struct.unpack(_SUBSHELL_FMT, f.read(_SUBSHELL_SIZE)))
        self._subshell = subshell

        self._u_data_offset = f.tell()
        self._file = f  # kept open, see class docstring

    def _find(self, z, n, ell):
        offset, count = self._element[z - 1]
        for i in range(offset, offset + count):
            if self._subshell[i] == (n, ell):
                return i
        return -1

    def has(self, z, n, ell):
        return self._find(z, n, ell) >= 0

    def source(self, z, n, ell):
        i = self._find(z, n, ell)
        if i < 0:
            raise KeyError((z, n, ell))
        self._file.seek(self._u_data_offset + i * 4 * self.grid_size)
        u = array.array('f', self._file.read(4 * self.grid_size))
        return RadialSource(self.r, u)

    def config(self, z):
        offset, count = self._element[z - 1]
        return self._subshell[offset:offset + count]


def load(path=DEFAULT_PATH):
    return HfsTables(path)
