"""Clementi-Raimondi size-calibration factors for the atom cloud (HFS-table model),
indexed by Z-1 (Z=1..92, the display range cap -- slater.MAX_DISPLAY_Z).
Scaling the cloud coordinates by FACTOR[z-1] makes the valence subshell mode
radius land on the Clementi-Raimondi literature value, keeping the model's own
internal shell structure. Elements without a CR value (Fr, Ra) are 1.0.

Same factors as src/physics/atom_size_calib.h (device C++). Consumed ONLY by
micropython/atom_view.py, which renders through hfs_radial_tables.py's tables
the same way the device does -- see pc/RUN_HFS.md's device note.

GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
"""

FACTOR = (
    0.4402, 0.4433, 0.6834, 0.6927, 0.5710, 0.5575, 0.5678, 0.5702,
    0.5723, 0.5806, 0.7579, 0.7684, 0.5610, 0.6560, 0.6853, 0.7085,
    0.7190, 0.7219, 0.8262, 0.8325, 0.8457, 0.8597, 0.8721, 0.8219,
    0.8843, 0.8902, 0.8905, 0.8953, 0.8290, 0.8978, 0.6664, 0.7276,
    0.7601, 0.7648, 0.7647, 0.7826, 0.8640, 0.8662, 0.9178, 0.9404,
    0.8964, 0.8902, 0.9395, 0.8852, 0.8768, 1.8737, 0.8642, 0.9309,
    0.7145, 0.7665, 0.7881, 0.8029, 0.8077, 0.8202, 0.8850, 0.8980,
    0.7453, 0.7155, 0.9217, 0.7764, 0.7800, 0.9137, 0.8945, 0.9627,
    0.8862, 0.9055, 0.9051, 0.9127, 0.9041, 0.9118, 0.9575, 0.9615,
    0.9652, 0.9646, 0.9632, 0.9696, 0.9640, 0.9123, 0.9096, 0.9749,
    0.6994, 0.7862, 0.8107, 0.8254, 0.8403, 0.8384, 1.0000, 1.0000,
    0.7093, 0.6889, 0.6733, 0.6608,
)
