// Clementi-Raimondi size-calibration factors for the atom point cloud, indexed by
// Z-1 (Z=1..92, the display range cap -- see periodic_grid.h's kMaxDisplayZ).
// Scaling a rendered cloud's coordinates by kAtomSizeCalibFactor[z-1] makes its
// valence subshell mode radius land on the Clementi-Raimondi literature value
// (pc/clementi_radii.py), keeping the model's own internal shell structure.
// HFS-table factors (compute_table_factors()): f = CR_lit / HFS-table valence
// mode (pc/hfs_tables_reduced.npz, the same tables src/hfs_radial.h renders
// through) -- elements without a CR value (Fr, Ra) are 1.0. See pc/RUN_HFS.md
// and pc/atom_view_pc.py's clementi_size_factor for the PC sibling.
//
// GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
#pragma once

#include "physics/orbitals.h" // orb_real_t

inline constexpr int kAtomSizeCalibCount = 92;

inline constexpr orb_real_t kAtomSizeCalibFactor[92] = {
    orb_real_t(0.4402), orb_real_t(0.4433), orb_real_t(0.6834), orb_real_t(0.6927),
    orb_real_t(0.5710), orb_real_t(0.5575), orb_real_t(0.5678), orb_real_t(0.5702),
    orb_real_t(0.5723), orb_real_t(0.5806), orb_real_t(0.7579), orb_real_t(0.7684),
    orb_real_t(0.5610), orb_real_t(0.6560), orb_real_t(0.6853), orb_real_t(0.7085),
    orb_real_t(0.7190), orb_real_t(0.7219), orb_real_t(0.8262), orb_real_t(0.8325),
    orb_real_t(0.8457), orb_real_t(0.8597), orb_real_t(0.8721), orb_real_t(0.8219),
    orb_real_t(0.8843), orb_real_t(0.8902), orb_real_t(0.8905), orb_real_t(0.8953),
    orb_real_t(0.8290), orb_real_t(0.8978), orb_real_t(0.6664), orb_real_t(0.7276),
    orb_real_t(0.7601), orb_real_t(0.7648), orb_real_t(0.7647), orb_real_t(0.7826),
    orb_real_t(0.8640), orb_real_t(0.8662), orb_real_t(0.9178), orb_real_t(0.9404),
    orb_real_t(0.8964), orb_real_t(0.8902), orb_real_t(0.9395), orb_real_t(0.8852),
    orb_real_t(0.8768), orb_real_t(1.8737), orb_real_t(0.8642), orb_real_t(0.9309),
    orb_real_t(0.7145), orb_real_t(0.7665), orb_real_t(0.7881), orb_real_t(0.8029),
    orb_real_t(0.8077), orb_real_t(0.8202), orb_real_t(0.8850), orb_real_t(0.8980),
    orb_real_t(0.7453), orb_real_t(0.7155), orb_real_t(0.9217), orb_real_t(0.7764),
    orb_real_t(0.7800), orb_real_t(0.9137), orb_real_t(0.8945), orb_real_t(0.9627),
    orb_real_t(0.8862), orb_real_t(0.9055), orb_real_t(0.9051), orb_real_t(0.9127),
    orb_real_t(0.9041), orb_real_t(0.9118), orb_real_t(0.9575), orb_real_t(0.9615),
    orb_real_t(0.9652), orb_real_t(0.9646), orb_real_t(0.9632), orb_real_t(0.9696),
    orb_real_t(0.9640), orb_real_t(0.9123), orb_real_t(0.9096), orb_real_t(0.9749),
    orb_real_t(0.6994), orb_real_t(0.7862), orb_real_t(0.8107), orb_real_t(0.8254),
    orb_real_t(0.8403), orb_real_t(0.8384), orb_real_t(1.0000), orb_real_t(1.0000),
    orb_real_t(0.7093), orb_real_t(0.6889), orb_real_t(0.6733), orb_real_t(0.6608),
};
