// Clementi-Raimondi size-calibration factors for the atom point cloud, indexed by
// Z-1 (Z=1..92, the display range cap -- see periodic_grid.h's kMaxDisplayZ).
// Scaling a rendered cloud's coordinates by kAtomSizeCalibFactor[z-1] makes its
// valence subshell mode radius land on the Clementi-Raimondi literature value
// (pc/clementi_radii.py), keeping the model's own internal shell structure.
// HFS-table factors (compute_table_factors()): f = CR_lit / HFS-table valence
// mode (pc/hfs_tables_reduced.npz, the same tables src/physics/hfs_radial.h renders
// through) -- elements without a CR value (Fr, Ra) are 1.0. See pc/RUN_HFS.md
// and pc/atom_view_pc.py's clementi_size_factor for the PC sibling.
//
// GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
#pragma once

#include "physics/orbitals.h" // orb_real_t

inline constexpr int kAtomSizeCalibCount = 92;

inline constexpr orb_real_t kAtomSizeCalibFactor[92] = {
    orb_real_t(0.9436), orb_real_t(1.0240), orb_real_t(1.0026), orb_real_t(1.0281),
    orb_real_t(1.0482), orb_real_t(1.0600), orb_real_t(1.0862), orb_real_t(1.1056),
    orb_real_t(1.1190), orb_real_t(1.1484), orb_real_t(1.1012), orb_real_t(1.0805),
    orb_real_t(0.8374), orb_real_t(0.9743), orb_real_t(1.0086), orb_real_t(1.0368),
    orb_real_t(1.0369), orb_real_t(1.0285), orb_real_t(1.1230), orb_real_t(1.0912),
    orb_real_t(1.1133), orb_real_t(1.1375), orb_real_t(1.1631), orb_real_t(1.1260),
    orb_real_t(1.1986), orb_real_t(1.2096), orb_real_t(1.2170), orb_real_t(1.2335),
    orb_real_t(1.1759), orb_real_t(1.2618), orb_real_t(1.0082), orb_real_t(1.0600),
    orb_real_t(1.0747), orb_real_t(1.0694), orb_real_t(1.0514), orb_real_t(1.0612),
    orb_real_t(1.1527), orb_real_t(1.1149), orb_real_t(1.1698), orb_real_t(1.2087),
    orb_real_t(1.1751), orb_real_t(1.1715), orb_real_t(1.2250), orb_real_t(1.1838),
    orb_real_t(1.1788), orb_real_t(2.8822), orb_real_t(1.1796), orb_real_t(1.2450),
    orb_real_t(1.0276), orb_real_t(1.0555), orb_real_t(1.0572), orb_real_t(1.0558),
    orb_real_t(1.0521), orb_real_t(1.0456), orb_real_t(1.1486), orb_real_t(1.1232),
    orb_real_t(0.9276), orb_real_t(0.8976), orb_real_t(1.1546), orb_real_t(0.9781),
    orb_real_t(0.9888), orb_real_t(1.1668), orb_real_t(1.1460), orb_real_t(1.2169),
    orb_real_t(1.1376), orb_real_t(1.1636), orb_real_t(1.1641), orb_real_t(1.1749),
    orb_real_t(1.1650), orb_real_t(1.1761), orb_real_t(1.2344), orb_real_t(1.2321),
    orb_real_t(1.2292), orb_real_t(1.2319), orb_real_t(1.2452), orb_real_t(1.2539),
    orb_real_t(1.2476), orb_real_t(1.2117), orb_real_t(1.2137), orb_real_t(1.2716),
    orb_real_t(0.9738), orb_real_t(1.0572), orb_real_t(1.0612), orb_real_t(1.0670),
    orb_real_t(1.0595), orb_real_t(1.0632), orb_real_t(1.0000), orb_real_t(1.0000),
    orb_real_t(0.8691), orb_real_t(0.8438), orb_real_t(0.8270), orb_real_t(0.8152),
};
