/**
 * @file hfs_radial.h
 * @brief Device-side loader and table-fed radial samplers for the screened-potential
 *        (HFS/atomSFE) atom model -- direct port of pc/hfs_tables.py's RadialSource/HfsTables
 *        (lookup) and micropython/atom_cloud.py's `radial_tables` branch (sampler
 *        construction), see that file's build_atom_point_cloud() docstring for the model.
 *        MicroPython counterpart: micropython/hfs_radial_tables.py -- same on-demand-from-
 *        flash reading strategy, see that module's docstring.
 *
 * Data/logic split mirrors font.h/font_data.h (see CLAUDE.md section 4.1), except the "data"
 * half is no longer a compiled-in header: src/hfs_tables.h (GENERATED by
 * tools/hfs_table_gen.py, do not hand-edit) holds only the three size constants; the actual
 * per-(Z,n,l) u(r) data lives in data/hfs_tables.bin, flashed to the "storage" SPIFFS
 * partition (partitions_16M.csv) via `pio run -t uploadfs` and read from there ON DEMAND by
 * hfs_radial.cpp (hand-written) -- not linked into the firmware image as .rodata. This trades
 * a small amount of per-lookup latency (one file open/seek/read, done once per element switch,
 * not once per frame or per sampled point) for a firmware image that doesn't carry ~470KB of
 * data that rarely changes, and for RAM that never holds more than the current element's
 * subshells (a few KB) instead of nothing extra either way (the array was .rodata before, so
 * this is a flash-image-size/OTA-size trade, not a RAM one).
 *
 * Coverage is exactly Z=1..92 (kHfsElementCount, matching periodic_grid.h's kMaxDisplayZ) --
 * every element atom_cloud.cpp ever renders has a table entry, verified 92/92 against the
 * NIST configurations by pc/RUN_HFS.md section 5's cross-check. hfsFindU() also returns
 * nullptr (triggering the SAME hydrogenic fallback atom_cloud.cpp already has) if the
 * "storage" partition isn't mounted or data/hfs_tables.bin hasn't been uploaded yet (see
 * hfsInit()) -- so a board that hasn't run `pio run -t uploadfs` still boots and renders,
 * just with the old hydrogenic radii until it has.
 */
#pragma once

#include "physics/hfs_tables.h" // kHfsGridSize/kHfsElementCount/kHfsSubshellCount
#include "physics/pointcloud.h"

/**
 * Ensures the "storage" SPIFFS partition is mounted and the small header/index (r grid +
 * element/subshell tables, a few KB total) is loaded into RAM from data/hfs_tables.bin.
 * Idempotent (safe to call every time, from any boot path -- chooser, ATOM_VIEW_TEST,
 * BENCHMARK_TEST, ...) and non-fatal on failure (logs and leaves the table unavailable, same
 * "debug/optional feature degrades gracefully" convention as screenshot::init()). Called
 * lazily by hfsFindU() on first use, so no caller needs to remember to call this explicitly;
 * exposed here only so a caller that wants the mount/load cost paid predictably (e.g. at boot,
 * off the render path) can call it early.
 */
void hfsInit();

/**
 * Find subshell (n, ell) of element z (1 <= z <= kHfsElementCount) and read its u(r) row from
 * flash into a shared per-call scratch buffer (kHfsGridSize entries).
 *
 * @return  Pointer to the row, valid ONLY until the next hfsFindU() call (not reentrant, same
 *          convention as pointcloud.h's buildRadialSamplerRuntime() -- safe for
 *          atom_cloud.cpp's sequential per-group loop, which consumes the pointer immediately
 *          via buildHfsRadialSamplerIsotropic()/buildHfsRadialSamplerOriented() before the
 *          next group's hfsFindU() call). nullptr if the table isn't available (see hfsInit())
 *          or the subshell isn't present -- shouldn't happen for any (n, ell)
 *          buildAtomPointCloud() produces from slater.h's electronConfiguration(z) for z<=92
 *          (see this file's header comment); callers should fall back to the hydrogenic model
 *          in either case.
 */
[[nodiscard]] const orb_real_t *hfsFindU(int z, int n, int ell);

/**
 * R(r) = u(r)/r by linear interpolation on the loaded grid -- port of pc/hfs_tables.py's
 * RadialSource.R_lookup(). `u` must be hfsFindU()'s most recent return value (see its
 * docstring for the validity window).
 */
[[nodiscard]] orb_real_t hfsRLookup(orb_real_t r, const orb_real_t *u);

/**
 * Radial sampler for a FULL subshell (isotropic path): the inverse CDF built DIRECTLY on the
 * table's own log-uniform grid from density = u^2 -- port of
 * micropython/atom_cloud.py's `radial_tables is not None` branch under `if m is None`, which
 * calls pointcloud.init_radial_sampler_from_table(x_grid, density).
 *
 * Not reentrant (single static instance, reused every call) -- same convention as
 * pointcloud.h's buildRadialSamplerRuntime(), safe for atom_cloud.cpp's sequential per-group
 * loop only.
 */
[[nodiscard]] const RadialTable &buildHfsRadialSamplerIsotropic(const orb_real_t *u);

/**
 * Radial sampler for a Hund's-rule (anisotropic, partially-filled subshell) group: R_lookup
 * evaluated at kOrbitalTableSize evenly-spaced r in [0, maxR], then the ordinary evenly-spaced
 * buildInverseCdf() -- port of micropython/atom_cloud.py's `radial_tables is not None` branch
 * under `else` (the Hund path), which calls
 * pointcloud.init_orbital_sampler(radial_fn=src.R_lookup, max_r=...).
 *
 * Deliberately NOT the direct-grid path above -- mirrors an asymmetry already present in the
 * Python model (init_orbital_sampler()'s shared hydrogenic/tabulated signature always samples
 * evenly in r, only init_radial_sampler_from_table() samples the grid directly), not something
 * to "fix" here, just to port faithfully (see this project's CLAUDE.md on staying aligned with
 * the Python ports).
 *
 * Not reentrant, same convention as buildHfsRadialSamplerIsotropic() above (separate static
 * storage from it, since both may be needed across different groups within one
 * buildAtomPointCloud() call, just never concurrently).
 */
[[nodiscard]] const RadialTable &buildHfsRadialSamplerOriented(const orb_real_t *u);
