// Screened-potential (HFS/atomSFE) radial table SIZE CONSTANTS -- the actual
// per-(Z,n,l) u(r) data lives in data/hfs_tables.bin (ESP32 SPIFFS,
// `pio run -t uploadfs`) / micropython/hfs_tables.bin (MicroPython device
// root), read on demand by src/hfs_radial.cpp -- see that file's header
// comment for the binary format and read strategy, and this file's own
// generator (tools/hfs_table_gen.py) for the schema/provenance.
//
// GENERATED by tools/hfs_table_gen.py from pc/hfs_tables_reduced.npz --
// do not edit by hand.
#pragma once

inline constexpr int kHfsGridSize = 128;
inline constexpr int kHfsElementCount = 92;
inline constexpr int kHfsSubshellCount = 915;
